### ISSUE TITLE
Make Vanilla version of the lamp

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/genie#15]
@tjacobdesign may help with this! Thanks!

**Comment by tom2strobl** [comment]
Hey guys, I know it's almost a year later, but is there anything, even unfinished code lying around? It's just way too sad that one can pretty much only use genie if going Angular. I honestly don't understand how something that awesome only has 220 stars (of today). If there was anything you started vanilla/jQuery like, just drop it in some secret branch or so, would appreciate it!

**Comment by tjacobdesign** [comment]
@tom2strobl yup, as you can see, I started on it months ago. I've got a fork right here: https://github.com/tjacobdesign/genie

I got the basic structure and functionality working in VanillaJS, just ran out of time to get all the details right (not to mention testing). I might have a little more work done locally on my home computer, I'll check tonight and push if I have anything of consequence.

**Comment by kentcdodds** [comment]
Thanks for your interest in the project @tom2strobl! I'm not currently using this library, but I would like to get into it again, so let me know if you need any help.

**Comment by tom2strobl** [comment]
Thanks guys, again – I'm very surprised that genie is kind of a hidden secret in the github universe. I'm using it as part of a Meteor.js app and now made a quick "custom lamp" by abusing [sergext/meteor-typeahead](https://github.com/sergeyt/meteor-typeahead), but it's not really something worthy of a PR because it's basically just glueing those two things together without any magic. In the unlikely case someone else finds himself in the same situation, here's a gist how I did it: [tom2strobl/427205db64360c1f916f](https://gist.github.com/tom2strobl/427205db64360c1f916f)
Keep up the good work @kentcdodds and @tjacobdesign!
